// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebtmipjckhkqkllgzxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidG1pcGpja2hrcWtsbGd6eHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODU0NTEsImV4cCI6MjA2MzY2MTQ1MX0.PExEqn-6ju9DS9v9bhXi-SdH5_hyj1moFx8cO6u1U7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);