// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pssbqnffyvswbfkfnuga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc2JxbmZmeXZzd2Jma2ZudWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODMyNjQsImV4cCI6MjA2MzY1OTI2NH0.2gtmGQGYVmJ9a-lEeYcv2Xs1dnorAqO0kt5BBn_E6Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);